/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bch_crc_check_ant_chooser_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c917bdf75de12879386344de0a709827)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/bch_crc_check_ant_chooser_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bch_crc_check_ant_chooser_bb_pydoc.h>

void bind_bch_crc_check_ant_chooser_bb(py::module& m)
{

    using bch_crc_check_ant_chooser_bb    = gr::lte::bch_crc_check_ant_chooser_bb;


    py::class_<bch_crc_check_ant_chooser_bb,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<bch_crc_check_ant_chooser_bb>>(m, "bch_crc_check_ant_chooser_bb", D(bch_crc_check_ant_chooser_bb))

        .def(py::init(&bch_crc_check_ant_chooser_bb::make),
           py::arg("name") =  "bch_crc_check_ant_chooser_bb",
           D(bch_crc_check_ant_chooser_bb,make)
        )
        



        ;




}








