/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mib_unpack_vbm.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(95f6ace7afaa01184fdf7029de9ff28e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/mib_unpack_vbm.h>
// pydoc.h is automatically generated in the build directory
#include <mib_unpack_vbm_pydoc.h>

void bind_mib_unpack_vbm(py::module& m)
{

    using mib_unpack_vbm    = gr::lte::mib_unpack_vbm;


    py::class_<mib_unpack_vbm,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<mib_unpack_vbm>>(m, "mib_unpack_vbm", D(mib_unpack_vbm))

        .def(py::init(&mib_unpack_vbm::make),
           py::arg("name") =  "mib_unpack_vbm",
           D(mib_unpack_vbm,make)
        )
        



        ;




}








