/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mimo_pss_tagger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(21b77b6151212e179e897f8595d3a065)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/mimo_pss_tagger.h>
// pydoc.h is automatically generated in the build directory
#include <mimo_pss_tagger_pydoc.h>

void bind_mimo_pss_tagger(py::module& m)
{

    using mimo_pss_tagger    = gr::lte::mimo_pss_tagger;


    py::class_<mimo_pss_tagger,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<mimo_pss_tagger>>(m, "mimo_pss_tagger", D(mimo_pss_tagger))

        .def(py::init(&mimo_pss_tagger::make),
           py::arg("fftl"),
           D(mimo_pss_tagger,make)
        )
        



        ;




}








