/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mimo_remove_cp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(eddc7b18ce2db8992caf6e3e9306f564)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/mimo_remove_cp.h>
// pydoc.h is automatically generated in the build directory
#include <mimo_remove_cp_pydoc.h>

void bind_mimo_remove_cp(py::module& m)
{

    using mimo_remove_cp    = gr::lte::mimo_remove_cp;


    py::class_<mimo_remove_cp,
        gr::block,
        gr::basic_block,
        std::shared_ptr<mimo_remove_cp>>(m, "mimo_remove_cp", D(mimo_remove_cp))

        .def(py::init(&mimo_remove_cp::make),
           py::arg("fflt"),
           py::arg("rxant"),
           py::arg("key"),
           D(mimo_remove_cp,make)
        )
        



        ;




}








