/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pbch_descrambler_vfvf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2a794f858afa2bbf2dd94e001e3a5611)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/pbch_descrambler_vfvf.h>
// pydoc.h is automatically generated in the build directory
#include <pbch_descrambler_vfvf_pydoc.h>

void bind_pbch_descrambler_vfvf(py::module& m)
{

    using pbch_descrambler_vfvf    = gr::lte::pbch_descrambler_vfvf;


    py::class_<pbch_descrambler_vfvf,
        gr::sync_interpolator,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<pbch_descrambler_vfvf>>(m, "pbch_descrambler_vfvf", D(pbch_descrambler_vfvf))

        .def(py::init(&pbch_descrambler_vfvf::make),
           py::arg("key"),
           D(pbch_descrambler_vfvf,make)
        )
        



        ;




}








