/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pbch_demux_vcvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e12babda4b936ee58a84c23f13303669)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/pbch_demux_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <pbch_demux_vcvc_pydoc.h>

void bind_pbch_demux_vcvc(py::module& m)
{

    using pbch_demux_vcvc    = gr::lte::pbch_demux_vcvc;


    py::class_<pbch_demux_vcvc,
               gr::block,
               gr::basic_block,
        std::shared_ptr<pbch_demux_vcvc>>(m, "pbch_demux_vcvc", D(pbch_demux_vcvc))

        .def(py::init(&pbch_demux_vcvc::make),
           py::arg("N_rb_dl"),
           py::arg("rxant"),
           py::arg("name") =  "pbch_demux_vcvc",
           D(pbch_demux_vcvc,make)
        )
        .def("set_cell_id", &pbch_demux_vcvc::set_cell_id, py::arg("id"))
        ;
}