/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pcfich_demux_vcvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4e3ce60cf728442187fe44954952ef62)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/pcfich_demux_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <pcfich_demux_vcvc_pydoc.h>

void bind_pcfich_demux_vcvc(py::module& m)
{

    using pcfich_demux_vcvc    = gr::lte::pcfich_demux_vcvc;


    py::class_<pcfich_demux_vcvc,
        gr::block,
        gr::basic_block,
        std::shared_ptr<pcfich_demux_vcvc>>(m, "pcfich_demux_vcvc", D(pcfich_demux_vcvc))

        .def(py::init(&pcfich_demux_vcvc::make),
           py::arg("N_rb_dl"),
           py::arg("key"),
           py::arg("out_key"),
           py::arg("msg_buf_name"),
           py::arg("name") =  "pcfich_demux_vcvc",
           D(pcfich_demux_vcvc,make)
        )
        



        ;




}








