/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(remove_cp_cvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f77f7cd7f4595f6541e7023a863dd963)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/remove_cp_cvc.h>
// pydoc.h is automatically generated in the build directory
#include <remove_cp_cvc_pydoc.h>

void bind_remove_cp_cvc(py::module& m)
{

    using remove_cp_cvc    = gr::lte::remove_cp_cvc;


    py::class_<remove_cp_cvc,
        gr::block,
        gr::basic_block,
        std::shared_ptr<remove_cp_cvc>>(m, "remove_cp_cvc", D(remove_cp_cvc))

        .def(py::init(&remove_cp_cvc::make),
           py::arg("fftl"),
           py::arg("key"),
           py::arg("name") =  "remove_cp_cvc",
           D(remove_cp_cvc,make)
        )
        



        ;




}








