/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(repeat_message_source_vf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5643d7dd27a7ef79ca7da49bd949660b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/repeat_message_source_vf.h>
// pydoc.h is automatically generated in the build directory
#include <repeat_message_source_vf_pydoc.h>

void bind_repeat_message_source_vf(py::module& m)
{

    using repeat_message_source_vf    = gr::lte::repeat_message_source_vf;


    py::class_<repeat_message_source_vf,
        gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<repeat_message_source_vf>>(m, "repeat_message_source_vf", D(repeat_message_source_vf))

        .def(py::init(&repeat_message_source_vf::make),
           py::arg("vector_len"),
           py::arg("name") =  "repeat_message_source_vf",
           D(repeat_message_source_vf,make)
        )
        



        ;




}








