/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sss_symbol_selector_cvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(45127412203496a04353c6fba9d3350e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lte/sss_symbol_selector_cvc.h>
// pydoc.h is automatically generated in the build directory
#include <sss_symbol_selector_cvc_pydoc.h>

void bind_sss_symbol_selector_cvc(py::module& m)
{

    using sss_symbol_selector_cvc    = gr::lte::sss_symbol_selector_cvc;


    py::class_<sss_symbol_selector_cvc,
        gr::block,
        gr::basic_block,
        std::shared_ptr<sss_symbol_selector_cvc>>(m, "sss_symbol_selector_cvc", D(sss_symbol_selector_cvc))

        .def(py::init(&sss_symbol_selector_cvc::make),
           py::arg("fftl"),
           py::arg("name") =  "sss_symbol_selector_cvc",
           D(sss_symbol_selector_cvc,make)
        )
        



        ;




}








